# Generated by Django 3.1 on 2022-08-29 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='phone_no',
            new_name='phone_number',
        ),
    ]
