# Generated by Django 3.1 on 2022-09-30 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_variationmanager'),
        ('cart', '0002_auto_20220930_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='variations',
            field=models.ManyToManyField(blank=b'I01\n', to='store.Variation'),
        ),
    ]
