# Generated by Django 3.1 on 2022-08-28 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catagory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catagory',
            options={'verbose_name': 'catagory', 'verbose_name_plural': 'catagories'},
        ),
        migrations.AlterField(
            model_name='catagory',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
        migrations.AlterModelTable(
            name='catagory',
            table=None,
        ),
    ]
